@c -*-texinfo-*-
@c This file is part of Guile-SSH Reference Manual.
@c Copyright (C) 2014 Artyom V. Poptsov
@c See the file guile-ssh.texi for copying conditions.

@page
@node Type Index
@unnumbered Type Index

@printindex tp

@node Procedure Index
@unnumbered Procedure Index

@printindex fn

@node Concept Index
@unnumbered Concept Index

@printindex cp
