name: Ubuntu/Guile 2.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install guile-2.2 guile-2.2-libs guile-library
          sudo apt install guile-2.2-dev texinfo texlive
          sudo apt install automake autoconf
          sudo apt install libssh-dev
          sudo apt install libtool
          sudo apt install gcc-9
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Autoreconf
        run: autoreconf -vif
      - name: Configure
        run: ./configure
      - name: Make
        run: make -j$(nproc)
      - name: Run tests
        run: make -j$(nproc) check
      - name: Make distribution
        run: make -j$(nproc) distcheck
      - name: Upload the artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: guile-ssh
          compression-level: 0
          path: "guile-ssh-*.tar.gz"

