name: Ubuntu/Guile 3.0

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt -qy install \
              guile-3.0 \
              guile-3.0-libs \
              guile-3.0-dev \
              guile-library \
              texinfo \
              libssh-dev \
              libtool \
              texlive \
              gettext \
              make \
              automake \
              autoconf \
              gcc
      - uses: actions/checkout@v2
      - name: Autoreconf
        run: autoreconf -vif
      - name: Configure
        run: ./configure
      - name: Build
        run: make -j$(nproc)
      - name: Run tests
        run: make -j$(nproc) check
      - name: Make distribution
        run: make -j$(nproc) distcheck
      - name: Upload the artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: guile-ssh
          compression-level: 0
          path: "guile-ssh-*.tar.gz"
