---
# File: guix.yml
name: Guix/Guile 3.0
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-linux-gnu
            package: guile-ssh
          - target: x86_64-linux-gnu
            package: guile-ssh/libssh-0.8
          - target: x86_64-linux-gnu
            package: guile-ssh/libssh-0.9
          - target: x86_64-linux-gnu
            package: guile-ssh/libssh-0.11
          - target: x86_64-linux-gnu
            package: guile-ssh/libssh-0.12
          - target: x86_64-linux-gnu
            package: guile-ssh/libssh-0.10/gcrypt
          - target: aarch64-linux-gnu
            package: guile-ssh
          - target: riscv64-linux-gnu
            package: guile-ssh

    name: "${{ matrix.target }}/${{ matrix.package }}"

    steps:
      - uses: actions/checkout@v4
      - uses: PromyLOPh/guix-install-action@v1
        with:
          pullAfterInstall: false
      - name: Build "${{ matrix.target }}/${{ matrix.package }}"
        run: >-
          guix build -L .guix/modules
          -e '(@ (guile-ssh-packages) ${{ matrix.package }})'
          ${{ matrix.target != 'x86_64-linux-gnu' && format('--target={0}', matrix.target) || '' }}

# End of guix.yml
...
